Eason/Eason/Controllers/HomeController.cs
using Eason.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Eason.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        List<SelectListItem> progress;
        public HomeController()
        {
            UserInfo.Function = "Bulletin";
        }
        public ActionResult GoogleMap()
        {
            UserInfo.Function = "GoogleMap";

            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Edit(string serno)
        {
            ProjectItem vProj = new ProjectItem();
            vProj.Conditions = vProj.getCondition(ProjectItem.ncConditions.PJI_SERNO.ToString(), serno);
            List<ProjectItem> ProjList = vProj.View<ProjectItem>(vProj.getSQLStatement());

            ddlInit();

            return View(ProjList.First());
        }
        [HttpPost]
        public ActionResult Edit(string serno, FormCollection collection)
        {
            try
            {
                ProjectItem vProj = new ProjectItem();

                if (TryUpdateModel(vProj))
                {
                    vProj.Update<ProjectItem>(serno, collection);

                    return RedirectToAction("Index");
                }
                else
                {
                    ddlInit();

                    return View(vProj);
                }
            }
            catch
            {
                return View();
            }
        }
        private void ddlInit()
        {
            #region 進度
            progress = new List<SelectListItem>();

            for (int i = 0; i <= 100; i += 5)
            {
                progress.Add(new SelectListItem()
                {
                    Text = string.Format("{0}%", i),
                    Value = i.ToString()
                });
            }
            ViewBag.ProgressItem = progress;
            #endregion
        }
        public JsonResultPro LoadData(string frm_data)
        {
            Dictionary<string, string> collection = new JsonToDictionary(frm_data).Dictionary;

            ProjectItem vProj = new ProjectItem();
            vProj.Conditions = " 1=1 ";
            vProj.Conditions += " AND " + vProj.getCondition(ProjectItem.ncConditions.PJI_EMPNAME.ToString(), UserInfo.UserName);

            List<ProjectItem> ProjList = vProj.View<ProjectItem>(vProj.getSQLStatement());

            return new JsonResultPro(
                            new { data = ProjList },
                            JsonResultPro.DateTimeFormatType.ShortDateTime,
                            JsonRequestBehavior.DenyGet
                        );
        }

        #region Login

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Login(FormCollection loginModel)
        {               
            Employee systemuser = new Employee();

            if (!TryUpdateModel(systemuser))
            {
                return View();
            }

            systemuser.Conditions = systemuser.getCondition(Employee.ncConditions.EMP_NAME.ToString(), loginModel["EMP_NAME"]);

            List<Employee> EmpList = systemuser.View<Employee>(systemuser.getSQLStatement());

            if (EmpList.Count != 0)
            {
                systemuser = EmpList.First();
            }
            else
            {
                systemuser = null;
            }

            if (systemuser == null)
            {
                ModelState.AddModelError("", "請輸入正確的帳號或密碼!");
                return View();
            }

            Encrypt encrypt = new Encrypt(loginModel["EMP_PASSWORD"]);
            loginModel["EMP_PASSWORD"] = encrypt.Result;

            if (systemuser.EMP_PASSWORD.Equals(loginModel["EMP_PASSWORD"]))
            {
                this.LoginProcess(systemuser, loginModel);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "請輸入正確的帳號或密碼!");
                return View();
            }
        }
        private void LoginProcess(Employee user, FormCollection loginModel)
        {
            var now = DateTime.Now;

            var ticket = new FormsAuthenticationTicket(
                version: 1,
                name: user.EMP_NAME.ToString(),
                issueDate: now,
                expiration: now.AddMinutes(30),
                isPersistent: false,
                userData: "",
                cookiePath: FormsAuthentication.FormsCookiePath);

            var encryptedTicket = FormsAuthentication.Encrypt(ticket);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
            Response.Cookies.Add(cookie);


            user.Update<Employee>(user.EMP_SERNO, loginModel);

            UserInfo.LoginDTTM = DateTime.Parse(loginModel["EMP_LASTLOGINDTTM"]);
            UserInfo.UserName = user.EMP_NAME;
            UserInfo.Title = user.EMP_TITLE;
            UserInfo.UserSerno = user.EMP_SERNO;
        }
        #endregion

        #region Logout
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            //清除所有的 session
            Session.RemoveAll();

            //建立一個同名的 Cookie 來覆蓋原本的 Cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);

            //建立 ASP.NET 的 Session Cookie 同樣是為了覆蓋
            HttpCookie cookie2 = new HttpCookie("ASP.NET_SessionId", "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);

            FormCollection collection = new FormCollection();
            collection.Add("EMP_LASTLOGOUTDTTM",DateTime.Now.ToString());

            Employee vEmp = new Employee();
            vEmp.Update<Employee>(UserInfo.UserSerno, collection);

            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

Eason/Eason/Controllers/ProjectItemController.cs
using Eason.Models;
using Eason.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eason.Controllers
{
    [Authorize]
    public class ProjectItemController : Controller
    {
        List<SelectListItem> progress;
        DropDownList<Employee> EmployeeList;
        public ActionResult Index(ProjectItemViewModel viewModel, string PJT_Serno)
        {
            if (viewModel.SearchParameter == null)
            {
                viewModel.SearchParameter = new ProjectItemSearchModel();
                viewModel.SearchParameter.PJT_SERNO = PJT_Serno;
            }
            var result = new ProjectItemViewModel
            {
                SearchParameter = viewModel.SearchParameter
            };

            return View(result);
        }
        [HttpPost]
        public JsonResultPro LoadData(string frm_data)
        {
            Dictionary<string, string> collection = new JsonToDictionary(frm_data).Dictionary;

            ProjectItem vProj = new ProjectItem();
            vProj.Conditions = " 1=1 ";
            if (!string.IsNullOrEmpty((string)collection["PJT_SERNO"]))
                vProj.Conditions += " AND " + vProj.getCondition(ProjectItem.ncConditions.PJT_SERNO.ToString(), (string)collection["PJT_SERNO"]);

            List<ProjectItem> ProjList = vProj.View<ProjectItem>(vProj.getSQLStatement());

            return new JsonResultPro(
                            new { data = ProjList },
                            JsonResultPro.DateTimeFormatType.ShortDateTime,
                            JsonRequestBehavior.DenyGet
                        );
        }

        public ActionResult Create(string PJT_Serno)
        {
            ProjectItem vProj = new ProjectItem
            {
                PJT_SERNO = PJT_Serno
            };

            ddlInit();
            
            return View(vProj);
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                ProjectItem vProj = new ProjectItem();

                if (TryUpdateModel(vProj))
                {

                    vProj.Insert<ProjectItem>(collection);

                    return RedirectToAction("Index", new { PJT_Serno = collection["PJT_SERNO"] });
                }
                else
                {
                    ddlInit();

                    return View(vProj);
                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(string serno)
        {
            
            ProjectItem vProj = new ProjectItem();
            vProj.Conditions = vProj.getCondition(ProjectItem.ncConditions.PJI_SERNO.ToString(), serno);
            List<ProjectItem> ProjList = vProj.View<ProjectItem>(vProj.getSQLStatement());
            
            ddlInit();

            return View(ProjList.First());
        }
        [HttpPost]
        public ActionResult Edit(string serno, FormCollection collection)
        {
            try
            {
                ProjectItem vProj = new ProjectItem();

                if (TryUpdateModel(vProj))
                {
                    vProj.Update<ProjectItem>(serno, collection);

                    return RedirectToAction("Index", new { PJT_Serno = collection["PJT_SERNO"] });
                }
                else
                {
                    ddlInit();

                    return View(vProj);
                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(string serno)
        {
            
            ProjectItem vProj = new ProjectItem();
            vProj.Conditions = vProj.getCondition(ProjectItem.ncConditions.PJI_SERNO.ToString(), serno);
            List<ProjectItem> ProjList = vProj.View<ProjectItem>(vProj.getSQLStatement());

            return View(ProjList.First());
        }
        [HttpPost]
        public ActionResult Delete(string serno, FormCollection collection)
        {
            try
            {
                ProjectItem vProj = new ProjectItem();
                vProj.Delete<ProjectItem>(serno, collection);

                return RedirectToAction("Index", new { PJT_Serno = TempData["PJT_SERNO"] });
            }
            catch
            {
                return View();
            }
        }
        private void ddlInit()
        {
            #region 進度
            progress = new List<SelectListItem>();

            for (int i = 0; i <= 100; i += 5)
            {
                progress.Add(new SelectListItem()
                {
                    Text = string.Format("{0}%", i),
                    Value = i.ToString()
                });
            }
            ViewBag.ProgressItem = progress;
            #endregion

            #region 參與人員
            EmployeeList = new DropDownList<Employee>(new Employee(), "EMP_NAME", "EMP_NAME");
            ViewBag.ddlParticipant = EmployeeList.SelectListItem;
            #endregion
        }
    }
}

Eason/Eason/Views/Home/Edit.cshtml
@model Eason.Models.ProjectItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="purple">
                <i class="material-icons">assignment</i>
            </div>
            <div class="card-content">
                <h4 class="card-title">修改項目</h4>
                <form>
                    @Html.HiddenFor(model => model.PJT_SERNO)
                    <div class="row">
                        <div class="col-md-2 col-lg-2">
                            <div class="form-group label-floating">
                                @Html.LabelFor(model => model.PJI_NAME, new { @Class = "control-label" })
                                <div>
                                    @Html.TextBoxFor(model => model.PJI_NAME, new { @class = "form-control", placeholder = "" })
                                    @Html.ValidationMessageFor(model => model.PJI_NAME)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-1">
                            <div class="checkbox-radios">
                                @Html.LabelFor(model => model.PJI_ISDONE)
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(model => model.PJI_ISDONE, new { @type = "checkbox", @name = "optionsCheckboxes" })
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="checkbox-radios">
                                @Html.LabelFor(model => model.PJI_ISUAT)
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(model => model.PJI_ISUAT, new { @type = "checkbox", name = "optionsCheckboxes" })
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                            <div class="checkbox-radios">
                                @Html.LabelFor(model => model.PJI_ISUT)
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(model => model.PJI_ISUT, new { @type = "checkbox", name = "optionsCheckboxes" })
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1">
                                <div class="form-group label-floating">
                                    @Html.LabelFor(model => model.PJI_PROGRESS)
                                    <div>
                                        @Html.DropDownList("PJI_PROGRESS", (IEnumerable<SelectListItem>)ViewBag.ProgressItem, new { @class = "selectpicker", @data_style = "select-with-transition", @data_size = "5" })
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group label-floating">
                                @Html.LabelFor(model => model.PJI_EXPECTDTTM)
                                <div>
                                    @Html.TextBoxFor(model => model.PJI_EXPECTDTTM, new { @class = "form-control", placeholder = "" })
                                    @Html.ValidationMessageFor(model => model.PJI_EXPECTDTTM)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group label-floating">
                                @Html.LabelFor(model => model.PJI_FINALDTTM)
                                <div>
                                    @Html.TextBoxFor(model => model.PJI_FINALDTTM, new { @class = "form-control", placeholder = "" })
                                    @Html.ValidationMessageFor(model => model.PJI_FINALDTTM)
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group label-floating">
                                @Html.LabelFor(model => model.PJI_COMMENT, new { @Class = "control-label" })
                                <div>
                                    @Html.TextBoxFor(model => model.PJI_COMMENT, new { @class = "form-control", placeholder = "" })
                                    @Html.ValidationMessageFor(model => model.PJI_COMMENT)
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">確定修改</button>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#PJI_EXPECTDTTM').datetimepicker({
                format: 'YYYY/MM/DD',
                defaultDate: '@DateTime.Now.ToShortDateString()',
                showTodayButton: true,
                showClear: true,
                showClose: true,
            }),
            $('#PJI_FINALDTTM').datetimepicker({
                format: 'YYYY/MM/DD',
                defaultDate: '@DateTime.Now.AddDays(14).ToShortDateString()',
                showTodayButton: true,
                showClear: true,
                showClose: true,
            })
        });
    </script>
}

Eason/Eason/Views/Home/GoogleMap.cshtml
@{
    ViewBag.Title = "GoogleMap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts{
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTVwaDSKmJm1ia2ZF6ZwrosuaHKPSdIns"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initGoogleMaps();
    });
</script>
}

Eason/Eason/Views/Home/Index.cshtml
@*@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

@model Eason.ViewModels.ProjectItemViewModel

<div class="col-md-12">
    <div class="card">
        <div class="card-header card-header-icon" data-background-color="purple">
            <i class="material-icons">assignment</i>
        </div>
        <div class="card-content">
            <h4 class="card-title">我的工作項目</h4>
            <div class="toolbar">
                <!--        Here you can write extra buttons/actions for the toolbar              -->
                @*<div>
                    @using (Html.BeginForm("Index", "ProjectItem", FormMethod.Post, new { @Id = "searchForm" }))
                    {
                        @Html.HiddenFor(model => model.SearchParameter.PJT_SERNO)
                    }
                </div>
                <button class="btn btn-primary" onclick="location.href='@Url.Action("Create", "ProjectItem", new { PJT_Serno = Model.SearchParameter.PJT_SERNO})';">新增項目</button>*@
            </div>
            <div class="material-datatables">
                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_NAME)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_EMPNAME)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_UAT)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_ISDONE)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_ISUAT)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_ISUT)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_PROGRESS)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_EXPECTDTTM)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_FINALDTTM)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ProjectItem.PJI_COMMENT)
                            </th>
                            <th class="disabled-sorting">
                                
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatables').DataTable({
                "ajax": {
                    "url": "/Home/LoadData",
                    "type": "POST",
                    "dataType": "json",
                    "data": function (d) {
                        d.frm_data = JSON.stringify($('#searchForm').serializeArray());
                    }
                },
                "columns": [
                    { "data": "PJI_NAME", "autoWidth": true },
                    { "data": "PJI_EMPNAME", "autoWidth": true, },
                    { "data": "PJI_UAT", "autoWidth": true },
                    {
                        "data": "PJI_ISDONE", "autoWidth": true,
                        "render": checkBox
                    },
                    {
                        "data": "PJI_ISUAT", "autoWidth": true,
                        "render": checkBox
                    },
                    {
                        "data": "PJI_ISUT", "autoWidth": true,
                        "render": checkBox
                    },
                    { "data": "PJI_PROGRESS", "autoWidth": true },
                    { "data": "PJI_EXPECTDTTM", "autoWidth": true },
                    { "data": "PJI_FINALDTTM", "autoWidth": true },
                    { "data": "PJI_COMMENT", "autoWidth": true },
                    {
                        "data": null,"autoWidth":true,
                        "render": function (data, type, col, meta) {
                            if (type === 'display') {
                                return $('<a>')
                                   .wrapInner("<i class='material-icons'>edit</i>")
                                   .attr('href', '/Home/Edit?serno=' + col.PJI_SERNO)
                                   .addClass("btn btn-simple btn-warning btn-icon edit")
                                   .wrap('<div></div>')
                                   .parent()
                                   .html();
                            } else {
                                return data;
                            }
                        }
                    }
                ],
                "sDom": "Rlfrtip",  // resizable columns

                "pagingType": "full_numbers",
                "lengthMenu": [
                    [10, 25, 50, -1],
                    [10, 25, 50, "All"]
                ],
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search records",
                }

            });

            $('.card .material-datatables label').addClass('form-group');
        });

        var checkBox = function ( data, type, full, meta ) {
            var is_checked = data == true ? "checked" : "";
            return '<input type="checkbox" name="optionsCheckboxes" disabled ' + is_checked + ' />';
        }
    </script>
}