Eason/Eason/Controllers/ProjectListController.cs
using Eason.Models;
using Dapper;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using Eason.ViewModels;
using System.Web.Script.Serialization;
using Newtonsoft.Json;

namespace Eason.Controllers
{
    [Authorize]
    public class ProjectListController : Controller
    {
        private List<SelectListItem> progress;
        private DropDownList<Employee> EmployeeList;
        private DropDownList<Customer> CustList;
        private DropDownList typeList;

        public ProjectListController()
        {
            UserInfo.Function = "Project";
        }

        public ActionResult Index(ProjectListViewModel viewModel)
        {
            ddlInit();
            
            var result = new ProjectListViewModel
            {
                SearchParameter = viewModel.SearchParameter,
                PJT_CUSTOMER = CustList.SelectListItem,
                PJT_PARTICIPANT = EmployeeList.SelectListItem,
                PJT_TYPE = typeList.SelectListItem
            };

            return View(result);
        }
        [HttpPost]
        public JsonResultPro LoadData(string frm_data)
        {
            Dictionary<string, string> collection = new JsonToDictionary(frm_data).Dictionary;

            ProjectList vProj = new ProjectList();
            vProj.Conditions = " 1=1 ";
            if (!string.IsNullOrEmpty(collection["PJT_NAME"]))
                vProj.Conditions += " AND " + vProj.getCondition(ProjectList.ncConditions.PJT_NAME.ToString(), (string)collection["PJT_NAME"]);
            if (!string.IsNullOrEmpty(collection["PJT_TYPE"]))
                vProj.Conditions += " AND " + vProj.getCondition(ProjectList.ncConditions.PJT_TYPE.ToString(), (string)collection["PJT_TYPE"]);
            if (!string.IsNullOrEmpty(collection["PJT_PARTICIPANT"]))
                vProj.Conditions += " AND " + vProj.getCondition(ProjectList.ncConditions.PJT_PARTICIPANTS.ToString(), (string)collection["PJT_PARTICIPANT"]);
            if (!string.IsNullOrEmpty(collection["PJT_CUSTOMER"]))
                vProj.Conditions += " AND " + vProj.getCondition(ProjectList.ncConditions.PJT_CUSTOMER.ToString(), (string)collection["PJT_CUSTOMER"]);

            List<ProjectList> ProjList = vProj.View<ProjectList>(vProj.getSQLStatement());

            return new JsonResultPro(
                            new { data = ProjList }, 
                            JsonResultPro.DateTimeFormatType.ShortDateTime, 
                            JsonRequestBehavior.DenyGet
                        );
        }
        public ActionResult Details(string serno)
        {
            return RedirectToAction("Index", "ProjectItem", new { PJT_Serno = serno });
        }
        public ActionResult Create()
        {
            ddlInit();

            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        { 
            try
            {
                ProjectList ProjList = new ProjectList();

                if (TryUpdateModel(ProjList))
                {
                    ProjList.Insert<ProjectList>(collection);
                    
                    return RedirectToAction("Index");
                }
                else
                {
                    ddlInit();

                    return View(ProjList);
                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(string serno)
        {
            
            ProjectList vProj = new ProjectList();
            vProj.Conditions = vProj.getCondition(ProjectList.ncConditions.PJT_SERNO.ToString(), serno);
            List<ProjectList> ProjList = vProj.View<ProjectList>(vProj.getSQLStatement());

            ddlInit();

            return View(ProjList.First());
        }
        [HttpPost]
        public ActionResult Edit(string serno, FormCollection collection)
        {
            try
            {
                ProjectList ProjList = new ProjectList();

                if (TryUpdateModel(ProjList))
                {

                    ProjList.Update<ProjectList>(serno, collection);

                    return RedirectToAction("Index");
                }
                else
                {
                    ddlInit();

                    return View(ProjList);
                }

            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(string serno)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(string serno, FormCollection collection)
        {
            try
            {
                ProjectList vProj = new ProjectList();
                vProj.Delete<ProjectList>(serno, collection);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public JsonResultPro GetCustomerCode(string CustomerName)
        {
            Customer vCst = new Customer();
            vCst.Conditions = vCst.getCondition(Customer.ncConditions.CST_NAME.ToString(), CustomerName);
            List<Customer> CstList = vCst.View<Customer>(vCst.getSQLStatement());

            return new JsonResultPro(
                new { data = CstList.First().CST_CODE },
                JsonRequestBehavior.DenyGet
                );
        }
        private void ddlInit()
        {
            #region 進度
            progress = new List<SelectListItem>();

            for (int i = 0; i <= 100; i += 5)
            {
                progress.Add(new SelectListItem()
                {
                    Text = string.Format("{0}%", i),
                    Value = i.ToString()
                });
            }
            ViewBag.ProgressItem = progress;
            #endregion

            #region 參與人員
            EmployeeList = new DropDownList<Employee>(new Employee(), "EMP_NAME", "EMP_NAME");
            ViewBag.ddlParticipant = EmployeeList.SelectListItem;
            #endregion

            #region 客戶
            CustList = new DropDownList<Customer>(new Customer(), "CST_NAME", "CST_NAME");
            ViewBag.ddlCustomer = CustList.SelectListItem;
            #endregion

            #region 專案類型
            Dictionary<string, string> types = new Dictionary<string, string>();
            types.Add("需求", "需求");
            types.Add("問題", "問題");
            typeList = new DropDownList(types);
            ViewBag.ddlProjectType = typeList.SelectListItem;
            #endregion
        }
    }
}

Eason/Eason/Controllers/ReportsController.cs
using Eason.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Eason.Controllers
{
    public class ReportsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public FileResult Create()
        {
            rtProjectManagement rt = new rtProjectManagement();

            return File(Encoding.UTF8.GetBytes(rt.FinalContent), "application/ms-excel", rt.WorkbookName);
        }
    }
}

Eason/Eason/Views/Shared/0_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/datetime_Css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("專案清單", "Index", "ProjectList")</li>
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 內部專案控管</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datetime")
    @RenderSection("scripts", required: false)
</body>
</html>

Eason/Eason/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link rel="apple-touch-icon" sizes="76x76" href="../UI/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="../UI/img/favicon.png" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
    <title>Project Management</title>
    @Styles.Render("~/UI/css")
</head>
<body>
    <div class="wrapper">

        <div class="sidebar" data-active-color="purple" data-background-color="black" data-image="../UI/img/sidebar-1.jpg">
            <div class="logo">
                <a href="@Url.Action("Index", "Home")" class="simple-text">
                    MVC 5
                </a>
            </div>

            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li id="Bulletin">
                        <a href="@Url.Action("Index", "Home")">
                            <i class="material-icons">dashboard</i>
                            <p>佈告欄</p>
                        </a>
                    </li>
                    <li id="Project">
                        <a href="@Url.Action("Index", "ProjectList")">
                            <i class="material-icons">content_paste</i>
                            <p>專案清單</p>
                        </a>
                    </li>
                    <li id="Employee">
                        <a href="@Url.Action("Index", "Employee")">
                            <i class="material-icons">person</i>
                            <p>人員管理</p>
                        </a>
                    </li>
                    <li id="Customer">
                        <a href="@Url.Action("Index", "Customer")">
                            <i class="material-icons">library_books</i>
                            <p>客戶管理</p>
                        </a>
                    </li>
                    <li id="Voting">
                        <a href="@Url.Action("Index", "Customer")">
                            <i class="material-icons">pie_chart_outlined</i>
                            <p>投票系統</p>
                        </a>
                    </li>
                    <li id="Ordering">
                        <a href="@Url.Action("Index", "Customer")">
                            <i class="material-icons">local_dining</i>
                            <p>訂餐系統</p>
                        </a>
                    </li>
                    <li id="GoogleMap">
                        <a href="@Url.Action("GoogleMap","Home")">
                            <i class="material-icons">place</i>
                            <p>Google Map</p>
                        </a>
                    </li>
                    <li id="Report">
                        <a href="@Url.Action("Index","Reports")">
                            <i class="material-icons">place</i>
                            <p>報表中心</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Project Management</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            @*<li>
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">dashboard</i>
                                    <p class="hidden-lg hidden-md">Dashboard</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification">5</span>
                                    <p class="hidden-lg hidden-md">Notifications</p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Mike John responded to your email</a></li>
                                    <li><a href="#">You have 5 new tasks</a></li>
                                    <li><a href="#">You're now friend with Andrew</a></li>
                                    <li><a href="#">Another Notification</a></li>
                                    <li><a href="#">Another One</a></li>
                                </ul>
                            </li>*@
                            <li>
                                <a href="@Url.Action("Edit", "Employee")">
                                    <i class="material-icons">person</i>
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Logout","Home")">Logout</a>
                            </li>
                        </ul>

                        @*<form class="navbar-form navbar-right" role="search">
                            <div class="form-group  is-empty">
                                <input type="text" class="form-control" placeholder="Search">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i><div class="ripple-container"></div>
                            </button>
                        </form>*@
                    </div>
                </div>
            </nav>
            @if(UserInfo.Function!="GoogleMap")
            { 
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        @RenderBody()
                    </div>
                </div>
            </div>
            }
            @if (UserInfo.Function == "GoogleMap")
            { 
                <div id="map"></div>
            }
            <footer class="footer">
                <div class="container-fluid">
                    @*<nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                    </nav>*@
                    <p class="copyright pull-right">
                        &copy;
                        <script>document.write(new Date().getFullYear())</script> <a href="">EasonTech</a>, Project Management
                    </p>
                </div>
            </footer>
        </div>
    </div>
    @*<div class="fixed-plugin">
        <div class="dropdown show-dropdown">
            <a href="#" data-toggle="dropdown">
                <i class="fa fa-cog fa-2x"> </i>
            </a>
            <ul class="dropdown-menu">
                <li class="header-title"> Sidebar Filters</li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger active-color">
                        <div class="badge-colors text-center">
                            <span class="badge filter badge-purple" data-color="purple"></span>
                            <span class="badge filter badge-blue" data-color="blue"></span>
                            <span class="badge filter badge-green" data-color="green"></span>
                            <span class="badge filter badge-orange" data-color="orange"></span>
                            <span class="badge filter badge-red" data-color="red"></span>
                            <span class="badge filter badge-rose active" data-color="rose"></span>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="header-title">Sidebar Background</li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger background-color">
                        <div class="text-center">
                            <span class="badge filter badge-white" data-color="white"></span>
                            <span class="badge filter badge-black active" data-color="black"></span>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger">
                        <p>Sidebar Mini</p>
                        <div class="togglebutton switch-sidebar-mini">
                            <label>
                                <input type="checkbox" unchecked="">
                            </label>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="adjustments-line">
                    <a href="javascript:void(0)" class="switch-trigger">
                        <p>Sidebar Image</p>
                        <div class="togglebutton switch-sidebar-image">
                            <label>
                                <input type="checkbox" checked="">
                            </label>
                        </div>
                        <div class="clearfix"></div>
                    </a>
                </li>
                <li class="header-title">Images</li>
                <li class="active">
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../UI/img/sidebar-1.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../UI/img/sidebar-2.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../UI/img/sidebar-3.jpg" alt="" />
                    </a>
                </li>
                <li>
                    <a class="img-holder switch-trigger" href="javascript:void(0)">
                        <img src="../UI/img/sidebar-4.jpg" alt="" />
                    </a>
                </li>
            </ul>
        </div>
    </div>*@
</body>
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/UI/js")
@RenderSection("scripts", required: false)
</html>

<script type="text/javascript">
    $(document).ready(function () {
        $('#@UserInfo.Function').addClass('active');
    })
</script>